Allow specification of kernel, append and initrd.

diff --git a/startvm b/startvm
--- a/startvm
+++ b/startvm
@@ -18,6 +18,7 @@
 
 : ${KVM_BLK_OPTS:="-drive if=virtio,file=/image/image"}
 
+
 : ${KVM_OPTS:="\
   -nodefaults \
   -device virtio-balloon-pci,id=balloon0 \
@@ -29,7 +30,24 @@
   "}
   # -serial telnet::4555,server,nowait \
 
-: ${KVM_CPU_OPTS:="-m 1024 -smp 4,sockets=4,cores=1,threads=1"}
+: ${KVM_CPU_OPTS:="-m ${BYO_MEMORY-1024} -smp 4,sockets=4,cores=1,threads=1"}
+
+if [ -n "$BYO_KERNEL" ]; then
+  if [ ! -e "$BYO_KERNEL" ]; then
+    echo "Specified BYO_KERNEL=$BYO_KERNEL does not exist. Volume missing?"
+    sleep 5; exit 1
+  fi
+  KVM_OPTS="$KVM_OPTS -kernel $BYO_KERNEL "
+fi
+if [ -n "$BYO_INITRD" ]; then
+  if [ ! -e "$BYO_INITRD" ]; then
+    echo "Specified BYO_INITRD=$BYO_INITRD does not exist. Volume missing?"
+    sleep 5; exit 1
+  fi
+  KVM_OPTS="$KVM_OPTS -initrd $BYO_INITRD "
+fi
+[ -z "$BYO_APPEND" ] && BYO_APPEND="console=ttyS0"
+KVM_OPTS="$KVM_OPTS -append $BYO_APPEND "
 
 log () {
   case "$1" in
